# Github Library
github:
  name: KMPMail
  release: 2025
  namespace: com.michaelflisar.kmpmail
  license:
    name: Apache License 2.0
    path: blob/main/LICENSE

# Maven
maven:
  group-id: io.github.mflisar.kmpmail
  primary-artifact-id: library # used to detect latest release version of the library (dynamically on the published homepage)

# Modules - list of modules [artifact-id, description, path]
modules:
  - artifact-id: library
    description: This is a very small library that allows you to send feedback from an app without internet permission via email, either directly or via an unintrusive notification.
    path: library/library

# XCFrameworks [name, path, targets (ios, macos)]
xcframeworks: []